-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Qogir")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            passes = 4,
        },
        rounding = 13,
    },
    general = {
        gaps_in = 3,
        gaps_out = 5,
    },
    input = {
        kb_layout = "fr",
        kb_variant = "us",
        natural_scroll = false,
        touchpad = {
            natural_scroll = false,
        },
    },
    misc = {
        vrr = 1,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "1920x1080@143.85Hz",
    position = "-660x-30",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-2580x-30",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "1260x-30",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
