-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Qogir")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            passes = 4,
        },
        rounding = 13,
    },
    general = {
        gaps_in = 3,
        gaps_out = 5,
    },
    input = {
        kb_layout = "fr",
        kb_variant = "us",
        natural_scroll = false,
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- Keybinds
hl.unbind("SUPER + T")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("foot"))
hl.unbind("SUPER + E")
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("thunar"))
hl.unbind("SUPER + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.close())
